### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by nijikokun** [Nijikokun/breeze#7]
Rebuilt from the ground up Breeze fully supports Promises as it is built entirely on the Promise chain. It appears to be competing with Bluebird slightly on feature-set and functionality at this point, except Breeze does not intend to be an alias for promises but an enhancement to them.

This reduces the code by a factor of 3, so the code is 3x smaller, and more efficient giving us these amazing benefits:

- Multiple `catch` functions
- Passing `promise` directly
- Accepting `return` values rather than using `next`
- Returning promises instead of `next`

This also means that there is no more `next` callback.

## Roadmap

- [x] `Breeze` Class
- [x] `BreezeHelpers` Class
- [x] `BreezeCallable` Class
- [x] `.when(conditional, handler)`
- [x] `.then(handler)`
- [x] `.catch(onCatchMethod)`
- [x] `.catch(ErrorType, onCatchMethod)`
- [x] `.spread(handler)`
- [x] `.tap(handler)`
- [x] `.return(handler)`
- [x] `.get(index)`
- [x] `.each(promiseArray, handler)`
- [x] `.map(promiseArray)`
- [ ] Options support
- [x] Benchmarking support
- [ ] Debug support
- [ ] Documentation
- [ ] Tests

**Comment by nijikokun** [comment]
Pre-release is visible under the 2.0 branch:

https://github.com/nijikokun/breeze/tree/feat/2.0
